const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const stubs=new Map(),el=()=>({addEventListener(){},classList:{add(){},remove(){},toggle(){}},setAttribute(){},innerHTML:'',textContent:'',elements:{}});
const ctx={location:{href:"https://example.github.io/carnet/"},console,structuredClone,crypto,URL,Date,setTimeout,clearTimeout,document:{querySelector(s){if(!stubs.has(s))stubs.set(s,el());return stubs.get(s)},querySelectorAll(){return []},addEventListener(){}},window:{addEventListener(){},scrollTo(){}}};vm.createContext(ctx);
const run=s=>vm.runInContext(s,ctx);for(const f of ['seasons.js','seed-photo.js','foraging.js','produce-icons.js','ingredients.js','recipe-tools.js','editor-tools.js','app.js'])run(fs.readFileSync('outputs/Carnet-web/docs/'+f,'utf8').replace(/\ninit\(\);/,''));
assert.equal(run('SEASONS.flatMap(s=>[...s.fruits,...s.vegetables]).filter(n=>!PRODUCE_ART[n]).join(",")'),'');
assert.notEqual(run('PRODUCE_ART.Courgette'),run('PRODUCE_ART.Concombre'));assert.notEqual(run('PRODUCE_ART.Abricot'),run('PRODUCE_ART.Pêche'));
assert(run('FORAGING.filter(x=>x.kind==="nut").every(x=>PRODUCE_ART[x.name])'));
run('state={version:1,recipes:[seed()]}');
assert.equal(run('ingredientItems(state.recipes[0]).map(formatIngredient).join("\\n")'),run('state.recipes[0].ingredients'));
assert.equal(run('parseIngredient("200 à 300 g de farine").name'),'farine');
assert.equal(run('parseIngredient("2 gousses d’ail").name'),'ail');
assert.equal(run('quantityNumber("1/2")'),.5);assert.equal(run('quantityNumber("1,5")'),1.5);assert(run('Number.isNaN(quantityNumber("1/0"))'));
run('const quantities=[{...emptyIngredient(),name:"Farine",mode:"range",min:"200",max:"300",unit:"g"},{...emptyIngredient(),name:"Œufs",mode:"exact",amount:"2"},{...emptyIngredient(),name:"Sel",mode:"free",note:"selon le goût"}]');
assert.equal(run('ingredientError(quantities)'),'');assert.equal(run('formatIngredient(quantities[0])'),'Farine · 200 à 300 g');
run('const restored=validateState({...state,recipes:[{...state.recipes[0],ingredientItems:quantities}]})');
assert.deepEqual(JSON.parse(run('JSON.stringify(restored.recipes[0].ingredientItems)')),JSON.parse(run('JSON.stringify(quantities)')));
assert.throws(()=>run('validateIngredientItems([{...quantities[0],min:"400"}])'));
assert.throws(()=>run('validateIngredientItems([{...quantities[1],amount:"-1"}])'));
assert.throws(()=>run('validateIngredientItems([{...quantities[1],mode:"invalid"}])'));
assert(run('matchesSelection(state.recipes[0],["Courgette","tomate"],"all")'));
assert(!run('matchesSelection(state.recipes[0],["Courgette","Noix"],"all")'));
assert(run('matchesSelection(state.recipes[0],["Courgette","Noix"],"any")'));
assert(!run('hasIngredient({ingredients:"2 poireaux"},"poire")'));
assert(!run('hasIngredient({ingredients:"2 pommes de terre"},"Pomme")'));
assert(!run('hasIngredient({ingredients:"100 g de noix de coco"},"Noix")'));
assert(!run('hasIngredient({ingredients:"1 tasse de lait",title:"Tarte aux noisettes"},"Noisette")'));
assert(run('hasIngredient({ingredients:"3 œufs"},"oeuf")'));
assert(run('hasIngredient({ingredients:"250 g de cèpes"},"Champignon")'));
assert(run('ingredientCatalog().includes("ail")||ingredientCatalog().includes("Ail")'));
run('selectedIngredients=["Courgette","Tomate"];renderRecipes()');assert(stubs.get('#cards').innerHTML.includes('2/2 ingrédients'));
run('selectedIngredients=["Noix"];renderCards()');assert(stubs.get('#cards').innerHTML.includes('Aucune recette'));
run('month=0;seasonTab="foraging";showWholeYear=false;renderSeasons()');assert(stubs.get('#content').innerHTML.includes('Aucune période habituelle'));
run('showWholeYear=true;renderSeasons()');for(const name of ['Morille commune','Noisette','Chanterelle en tube'])assert(stubs.get('#content').innerHTML.includes(name));
assert(run('FORAGING.every(x=>x.months.every(m=>m>=1&&m<=12)&&x.source.startsWith("https://"))'));
console.log('PASS: all seasonal pictograms; exact, fractional, range and free quantities; legacy preservation; backup validation and round trip; all/any ingredient matching, accent/plural/whole-word matching and no title-only matches; ranked card output; empty winter calendar and whole-year view.');

assert.equal(run('parseQuantity("Farine","200 à 300 g").mode'),'range');
assert.equal(run('parseQuantity("Sel","une pincée").note'),'une pincée');
assert.equal(run('parseQuantity("Lait","1/2 l").amount'),'1/2');
assert.equal(run('parseQuantity("Tomate","").mode'),'free');
assert.throws(()=>run('validateSteps([{text:"Couper",kind:"Découpe",minutes:"-2"}])'));
run('const v13=validateState({version:1,pantry:["Tomates","tomate","Œufs"],recipes:[{...seed(),photos:[],stepItems:[{text:"Couper.",kind:"Découpe",minutes:"5"},{text:"Cuire.",kind:"Cuisson",minutes:"12"}]}]})');
assert.equal(run('v13.pantry.length'),2);assert.equal(run('v13.recipes[0].photos.length'),0);assert.equal(run('v13.recipes[0].stepItems[1].minutes'),'12');
run('state=v13;detailId=v13.recipes[0].id;renderDetail()');assert(!stubs.get('#content').innerHTML.includes('jar-panel'));assert(stubs.get('#content').innerHTML.includes('Cuisson'));
run('state.recipes[0].jarEnabled=true;renderDetail()');assert(stubs.get('#content').innerHTML.includes('jar-panel'));
run('view="fridge";detailId=null;selectedIngredients=[];renderRecipes()');assert(stubs.get('#cards').innerHTML.includes('sous la main'));
console.log('PASS v1.3: quantities, steps validation, pantry deduplication, no-photo state, conditional canning, empty fridge.');

for(const name of ['Œufs','farine','sel','poivre','Crème fraiche','Echalotte','Magret de canard','Bouillon de volaille','pommes de terre','huile d’olive'])assert(!run('ingredientSymbol('+JSON.stringify(name)+')').includes('M19 10v15'),name);
assert.equal(run('ingredientSymbol("Bouillon de volaille")'),run('produceIcon("Bouillon de volaille")'));
assert.equal(run('ingredientSymbol("noix de coco")'),run('produceIcon("Noix de coco")'));
assert.equal(run('ingredientSymbol("pommes de terre")'),run('produceIcon("Pomme de terre")'));
run('view="recipes";category="Dessert";renderRecipes()');assert(stubs.get('#content').innerHTML.includes('data-category="Dessert" aria-pressed="true"'));assert(!stubs.get('#content').innerHTML.includes('id="category"'));
console.log('PASS v1.4: ingredient icons, compound names, illustrated category buttons.');

assert.equal(run('validateWaits(undefined).length'),0);
assert.throws(()=>run('validateWaits([{kind:"Repos",duration:"",note:""}])'));
assert.throws(()=>run('validateWaits([{kind:"inconnu",duration:"2 h",note:""}])'));
run('const waits=[{kind:"Marinade",duration:"4 à 6 h",note:"Au réfrigérateur"},{kind:"Séchage à l’air libre",duration:"30 min",note:"Suivre les consignes de la recette"}];state.recipes[0].waitItems=waits;state=validateState(JSON.parse(JSON.stringify(state)))');
assert.equal(run('state.recipes[0].waitItems[0].duration'),'4 à 6 h');
run('detailId=state.recipes[0].id;renderDetail()');
const html=stubs.get('#content').innerHTML;
assert(html.indexOf('À prévoir avant de commencer')<html.indexOf('Les ingrédients'));
assert(html.indexOf('data-action="delete"')>html.indexOf('class="history"'));
assert.equal((html.match(/data-action="delete"/g)||[]).length,1);
assert(run('stepDisplay({kind:"Marinade",minutes:"",text:"Mélanger"})').includes('recipe-icon'));
assert.equal(run('validateSteps([{kind:"Séchage à l’air libre",minutes:"30",text:"Laisser sécher"}])[0].minutes'),'30');
assert.equal(run('waitSummary({...state.recipes[0],waitItems:[]})'),'');
console.log('PASS v1.5: waiting times validation and backup round-trip, optional section, bottom delete, new step kinds and icons.');
